; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32.git
board = seeed_xiao_esp32c6
framework = arduino
build_flags =
	-I src/gui/
	-I src/gui/ui
	-D EXTERNAL_ANTENNA=1
	-D AHTXX=0
	-D SHT3X=1
	-D LOG_ENABLED=1
	-D TEST_ENABLED=0
   -D WDT_ENABLED=1
	-D SERIAL_PORT=Serial
	-D SW_VERSION=\"1.0\"
	-D LV_LVGL_H_INCLUDE_SIMPLE=1
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
